# Generated by Django 5.1.5 on 2025-01-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='salesdata',
            old_name='revenue',
            new_name='total_sales',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='quantity_sold',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='gender',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
