# Generated by Django 5.1.5 on 2025-01-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_category_salesdata_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='customer_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
